Cleanup v2
akafliegdarmstadt/d39durchflusssensor pull request #4
Opened 2021-10-19 19:39 UTC by helo9

Concurrent PR for #3

2021-10-20 13:34 UTC, dernatsch requested changes

2021-10-20 13:34 UTC, dernatsch commented on src/d39_bt/d39_bt.c
> +	return bt_enable(bt_ready);
I don't quite get the API here.
`bt_enable` is given a function pointer *(void)(int), right?
If bt_ready now fails, does bt_enable also return the error code that bt_ready gives?

If so I think the error handling (printk) should be moved out of bt_ready. If not I need to think some more about it.
Any way I think it's not ideal that the handling is in bt_ready and not in the main loop.

2021-10-20 13:34 UTC, dernatsch commented on src/d39_bt/d39_bt.c
> +void d39_bt_send_msg(char *buf, size_t len) {
int d39_bt...

2021-10-20 13:34 UTC, dernatsch commented on src/config.h
> +/* GPIO */
Wouldn't hurt to add a `#pragma once` here

2021-10-20 13:34 UTC, dernatsch commented on src/d39_gpio/d39_gpio.c
> + * @param err Gets set to an error message in case of an error.
Out of date comments

2021-10-20 13:34 UTC, dernatsch commented on src/d39_gpio/d39_gpio.c
> + * @param err Gets set to a error message in case of an error.
Out of date

2021-10-20 13:34 UTC, dernatsch commented on src/main.c
> +	d39_bt_send_msg( &buf, 15);
random space before &

2021-10-20 13:48 UTC, helo9 commented on src/d39_bt/d39_bt.c
> +	return bt_enable(bt_ready);
From my understanding no, because bt initialization might take to long. therefore bt_enable is non blocking

2021-10-20 18:05 UTC, dernatsch commented on src/d39_bt/d39_bt.c
> +	return bt_enable(bt_ready);
Okay, so if the initialization in bt_enable fails, we don't get any feedback and don't try again.
How about we let bt_enable send a signal if it succeeds or fails and have the main thread wait for it?

Then we could retry on a fail

2021-10-23 21:51 UTC, helo9 commented on src/d39_bt/d39_bt.c
> +	return bt_enable(bt_ready);
Will take a look at other examples.

2021-10-23 23:53 UTC, dernatsch commented
Closes #3

2021-10-24 18:57 UTC, helo9 commented on src/main.c
> +	d39_bt_send_msg( &buf, 15);
fixed

2021-10-24 18:57 UTC, helo9 commented on src/d39_bt/d39_bt.c
> +void d39_bt_send_msg(char *buf, size_t len) {
wowowowow, fixed

2021-10-24 18:58 UTC, helo9 commented on src/d39_gpio/d39_gpio.c
> + * @param err Gets set to an error message in case of an error.
removed

2021-10-24 18:58 UTC, helo9 commented on src/d39_gpio/d39_gpio.c
> + * @param err Gets set to a error message in case of an error.
removed

2021-10-24 18:58 UTC, helo9 commented on src/config.h
> +/* GPIO */
sure, added

2021-10-24 18:59 UTC, helo9 commented on src/d39_bt/d39_bt.c
> +	return bt_enable(bt_ready);
Have some idea, how to do it, but would do this in anther PR and merge it now.

2021-10-24 19:01 UTC, merged